<section class="container">

                <div class="col-md-12  textoVender">
                    <h2>Términos y condiciones</h2>
                    <p>Autosencuotas.com se limita a la publicación de los productos, plan de ahorro y servicios que comercializan los siguientes concesionarias y/o agentes oficiales de las terminales automotrices: Margian S.A. concesionario oficial Fiat Auto para la promoción de Plan de ahorro para fines determinados, Matos S.A. agente oficial Plan Chevrolet, Concesionario Oficial Ford Guillermo Dietrich S.A., Concesionario Oficial Volkswagen Guillermo Dietrich S.A. , Concesionario Oficial Peugeot Le Meridien S.A., Concesionario Oficial Ranault Osvaldo Francisco Diaz S.A, Concesionario Oficial Citroen Guini S.A. , Concesionario Oficial Toyota Zento S.A., Concesionario Oficial Chery Autos del Plata S.A.Todos los planes de ahorro se realizan a través de una solicitud de adhesión en el concesionario oficial, siempre en forma directa con la administradora elegida; Los concesionarios ó agentes oficiales que publican sus productos en este sitio están autorizados a brindar asesoramiento y llenar la solicitud de adhesión para la administradora a la cual pertenecen los cuales son responsables por toda la información publicada.</p>

                    <h2>Marca Registrada</h2>
                    <p>El nombre registro de marca y logo "AUTO$ EN CUOTA$" y "AUTOS EN CUOTAS" del nomenclador marcario respectivamente, como así también de la denominación social homónima, son marcas registradas. Queda expresamente prohibido su reproducción total ó parcial en cualquier tipo de medio electrónico o grafico, sin previa autorización escrita de nuestra parte.</p>

                    <h2>Contenidos</h2>
                    <p>No queremos que los consumidores se sientan confundidos sobre si los servicios que reciben son proporcionados por nosotros o por terceros. Por lo tanto, nosotros protegemos nuestros derechos de propiedad intelectual y prohibimos el uso no autorizado de nuestras marcas de servicio, marcas de producto, y nombres comerciales por parte de terceros. Queda prohibido usar, copiar, reproducir, volver a publicar o publicar, poner en línea, transmitir, distribuir, registrar e intentar el registro o modificación de éstas o cualquier otras marcas que se encuentren en el sitio, incluyendo cualquier otra marca cuya similitud con nuestras marcas pueda causar confusión entre los consumidores. Esta prohibición incluye el uso de las marcas como meta etiquetas (meta tags), en nombres de dominio, y en otros sitios de Internet.</p>

                    <h2>Términos y Condiciones</h2>
                    <p>www.autosencuotas.com.ar/ no asume responsabilidad alguna por el incumplimiento de los términos y condiciones pactados por los vendedores y los compradores de los productos y/o servicios ofrecidos por terceros que en cada caso se detalla la razón social, para que el usuario investigue y se asesore respecto del mismo, mediante informes comerciales u otra forma que el mismo crea conveniente antes de realizar la contratación.</p>

                    <p>Usted mantendrá indemne a www.autosencuotas.com.ar/ y sus dependientes, de y contra todo daño y/o perjuicio, cualquiera fuese su naturaleza, derivado u ocasionado, directa o indirectamente, por la utilización de los servicios y/o por la compra de los productos ofrecidos en www.autosencuotas.com.ar/. Todo reclamo, cualquiera fuese su naturaleza, deberá dirigirse exclusivamente a los fabricantes y/o comerciantes de los productos y/o servicios ofrecidos, que en cada caso se detalla su razón social.</p>
                    <p>Usted acepta, por el hecho de registrarse y operar con www.autosencuotas.com.ar/, el derecho de comunicarse con Usted por vía electrónica o telefónica hasta que usted manifieste fehacientemente que no desea ser contactado por www.autosencuotas.com.ar/.</p>
                    <p>El contenido de la pantalla relativa a www.autosencuotas.com.ar/, junto con y sin que se considere una limitación, sus programas, bases de datos, redes y archivos son de propiedad de www.autosencuotas.com.ar/. Su uso indebido así como su reproducción serán objeto de las acciones judiciales que correspondan. El presente acuerdo no podrá ser interpretado como un mandato o que genere ningún tipo de relación entre www.autosencuotas.com.ar/ y Usted., La utilización de los servicios brindados por www.autosencuotas.com.ar/ no podrá, en ningún supuesto, ser interpretada como una autorización y/o concesión de licencia de los derechos intelectuales de www.autosencuotas.com.ar/ y/o de un tercero.</p>

                    <h2>Modalidad de contratación</h2>
                    <p>www.autosencuotas.com.ar/ pone gratuitamente a disposición de los usuarios, cierta información y/o publicaciones y cantidad de precios, suministrados por ciertos proveedores de determinados bienes y servicios que en cada caso se detalla. Si el usuario está interesado en adquirir alguno de los productos que publicita www.autosencuotas.com.ar/, deberá hacerlo saber a www.autosencuotas.com.ar/ a través de la opción existente en la página.</p>

                    <p>www.autosencuotas.com.ar/ informará al proveedor y/o vendedor del producto o servicio en que el usuario esté interesado a fin de que tal proveedor y/o vendedor contacte directamente al usuario. La remuneración que percibe www.autosencuotas.com.ar/ del proveedor está calculada sobre la comisión ventas que haga el proveedor a compradores que se presenten a comprar con un código de identificación provisto por www.autosencuotas.com.ar/. www.autosencuotas.com.ar/ no garantiza en modo alguno que el Proveedor respete tal precio o tales condiciones al momento de contratar y, en consecuencia, no se hace responsable de ningún gasto que hubiera podido realizar el usuario ni de ningún daño que hubiera podido sufrir el usuario sobre la base de su asunción de que tal precio o tales condiciones serían mantenidos. Debe tenerse presente que se debe cumplir con el artículo 7 de la Ley de 24.240 e informar la fecha precisa de comienzo y finalización de la oferta así como sus modalidades condiciones y limitaciones y, si el proveedor limita cuantitativamente su oferta, informar la cantidad con que cuenta para cubrirla; en caso de que se otorgue financiamiento deberá consignarse precio de contado, saldo de deuda, el total de los intereses a pagar, la tasa de interés efectiva anual, la forma de amortización de los intereses, otros gastos si los hubiere, cantidad de pagos a realizar y su periodicidad, gastos extras o adicionales si los hubiera y monto total financiado a pagar, todo lo que será responsabilidad del proveedor y no de www.autosencuotas.com.ar/.</p>

                    <h2>Advertencia respecto de los riesgos asociados con el uso de la red y de www.autosencuotas.com.ar/</h2>
                    <p>El uso de Internet y www.autosencuotas.com.ar/ implica la asunción de riesgos de daños al software y al hardware del usuario. Documentos y archivos pueden contener virus y, como es el caso de cualquier computadora interconectada, la computadora del usuario puede ser atacada por hackers que podrían tener acceso a la información contenida en la computadora del usuario, extraerla o dañarla. El envío de información a través de la red o a través de e-mails tiene el riesgo de que tal información pueda ser captada por un tercero. www.autosencuotas.com.ar/ no se hace responsable de las consecuencias que pudiera acarrear al usuario la asunción por parte del usuario de ese riesgo. </p>
                    <p>La aparición de links en www.autosencuotas.com.ar/ no implica ninguna garantía por parte de www.autosencuotas.com.ar/ sobre los productos, servicios, o programas contenidos en ninguna página o sitio vinculada por tales links. www.autosencuotas.com.ar/ no ha revisado ninguno de los websites que hacen link con su site y, en consecuencia no se hace responsable del contenido de páginas o websites que hagan link hacia o desde www.autosencuotas.com.ar/. En consecuencia, continuar con los links hacia cualquier otro website queda al exclusivo riesgo del usuario. </p>
                    <p>www.autosencuotas.com.ar/ no tiene obligación alguna de conservar ninguna información que haya hecho disponible a los usuarios ni que le haya sido enviada por los usuarios. </p>
                    <p>Las funciones contenidas en www.autosencuotas.com.ar/ y el acceso al mismo pueden ser interrumpidas en cualquier momento y contener errores. Los servidores de internet pueden contener virus. www.autosencuotas.com.ar/ no se hace responsable de las consecuencias que pudieran acarrear tales circunstancias.</p>
                    <p>Los presentes términos y condiciones se regirán por las leyes de la República Argentina. Las partes acuerdan que cualquier disputa o reclamo que surja de o con relación a, la conexión con la ejecución o cumplimiento de este Acuerdo, incluyendo sin limitación, cualquier disputa sobre la válidez, interpretación, exigibilidad o incumplimiento de este acuerdo sometiendolo a la jurisdicción de los tribunales de la Ciudad Autónoma de Buenos Aires. </p>
                    <p>Toda notificación u otra comunicación que deba efectuarse bajo el presente, deberá realizarse por escrito a www.autosencuotas.com.ar/: a la dirección Lima 385 Piso 9 de la Ciudad Autónoma de Buenos Aires.</p>



                </div>
        </section>